services:
  - type: web
    name: air-canada-lost-found-backend
    env: node
    buildCommand: |
      npm install
      node --experimental-specifier-resolution=node_modules node_modules/.bin/tsc
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: FRONTEND_URL
        value: https://air-canada-lost-found-frontend.onrender.com
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  - type: static
    name: air-canada-lost-found-frontend
    buildCommand: |
      cd frontend
      npm install
      npm run build
    publishDir: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://air-canada-lost-found-backend.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
